services:
  mjw_service:
    image: mjw_service:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mjw_service_container
    environment:
      DB_HOST: mjwdbvm.mjwsubnet.mjwvcn.oraclevcn.com
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - mjw_db
    networks:
      - mjw_network

  mjw_app:
    image: mjw_app:1.0.0
    build:
      context: ../mjw-app
      dockerfile: Dockerfile
    container_name: mjw_app_container
    depends_on:
      - mjw_service
    ports:
      - "3000:3000"
    networks:
      - mjw_network
