services:
  mjw_service:
    image: mjw_service:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mjw_service_container
    environment:
      DB_HOST: mjwdbvm.mjwsubnet.mjwvcn.oraclevcn.com
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - mjw_network

  mjw_app:
    image: mjw_app:1.0.0
    container_name: mjw_app_container
    build:
      context: ../mjw-app
      dockerfile: Dockerfile
      args:
        ENV_FILE: ${ENV_FILE:-.env}
    depends_on:
      - mjw_service
    environment:
      NODE_ENV: production
      MJW_SERVICE_HOST: mjw_service
      MJW_SERVICE_PORT: 8080
    env_file:
      # Specify the environment files as a list of strings
      - path: .env
        required: true
      - path: .env.docker.mjwapp
        required: false
    ports:
      - "3000:3000"
    networks:
      - mjw_network

  caddy:
    image: caddy:2
    restart: unless-stopped
    container_name: mjw_caddy_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mjw_network


networks:
  mjw_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:

