services:
  mjw_service:
    image: mjw_service:1.0.0
# Not building as moving images via scp
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: mjw_service_container
    environment:
      DB_HOST: mjwdbvm.mjwsubnet.mjwvcn.oraclevcn.com
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - mjw_network

  mjw_app:
    image: mjw_app:1.0.0
    container_name: mjw_app_container
    depends_on:
      - mjw_service
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - mjw_network

networks:
  mjw_network:
    driver: bridge
