spring:
  profiles:
    active: dev
  liquibase:
    default-schema: mjw_service
  mvc:
    problemDetails:
      enable: true
      defaultType: application/problem+json

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?user=mjwdbadmin&password=vf1p3nPRuibL
    username: mjwdbadmin
    password: vf1p3nPRuibL
    hostname: localhost
    port: 5432
    database: verceldb
    driverClassName: org.postgresql.Driver

  jackson:
    default-property-inclusion: NON_NULL

security:
  jwt:
    secret-key: b0eb0e5901c834a70ec6f500007417664bbf43a1a1bc4fead3c01444def5d6a9
    expiration-time: 86400000

