spring:
  profiles:
    active: dev
  mvc:
    problemDetails:
      enable: true
      defaultType: application/problem+json
  sql:
    init:
      mode: always
      schema-location: classpath:/schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://ep-bold-block-a4wmt5zw-pooler.us-east-1.aws.neon.tech:5432/verceldb?user=default&password=vf1p3nPRuibL
    username: default
    password: vf1p3nPRuibL
    hostname: ep-bold-block-a4wmt5zw-pooler.us-east-1.aws.neon.tech
    port: 5432
    database: verceldb
    driverClassName: org.postgresql.Driver


